Repository Hanium2023-WeB/starD-backend-refactoring, pull requests merged in 2024-12, with the labels that each got.

#62 feat: 관리자 기능 - 신고 관리 구현
  src/main/java/com/web/stard/domain/member/domain/entity/Member.java
  src/main/java/com/web/stard/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/web/stard/domain/reply/repository/ReplyRepository.java
  src/main/java/com/web/stard/domain/reply/service/impl/ReplyServiceImpl.java
  src/main/java/com/web/stard/domain/report/api/ReportController.java
  src/main/java/com/web/stard/domain/report/domain/dto/response/ReportResponseDto.java
  src/main/java/com/web/stard/domain/report/repository/ReportRepository.java
  src/main/java/com/web/stard/domain/report/service/ReportService.java
  src/main/java/com/web/stard/domain/report/service/impl/ReportServiceImpl.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
Labels: :sparkles: feature

#65 스터디 검색 조건 @RequestBody 대신 @RequestParam 사용
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/domain/dto/request/StudyRequestDto.java
  src/main/java/com/web/stard/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
Labels: :recycle: refactor

#66 feat: 관리자 기능 - 회원 관리 구현
  src/main/java/com/web/stard/domain/member/domain/entity/Member.java
  src/main/java/com/web/stard/domain/member/repository/InterestRepository.java
  src/main/java/com/web/stard/domain/member/repository/MemberRepository.java
  src/main/java/com/web/stard/domain/member/repository/ProfileRepository.java
  src/main/java/com/web/stard/domain/member/service/UnknownMemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/AuthServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/UnknownMemberService.java
  src/main/java/com/web/stard/domain/post/repository/PostRepository.java
  src/main/java/com/web/stard/domain/reply/repository/ReplyRepository.java
  src/main/java/com/web/stard/domain/report/api/ReportController.java
  src/main/java/com/web/stard/domain/report/domain/dto/response/ReportResponseDto.java
  src/main/java/com/web/stard/domain/report/repository/ReportRepository.java
  src/main/java/com/web/stard/domain/report/service/ReportService.java
  src/main/java/com/web/stard/domain/report/service/impl/ReportServiceImpl.java
  src/main/java/com/web/stard/domain/starScrap/repository/StarScrapRepository.java
  src/main/java/com/web/stard/domain/study/domain/entity/Study.java
  src/main/java/com/web/stard/domain/study/repository/StudyApplicantRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyRepository.java
  src/main/java/com/web/stard/domain/teamBlog/repository/StudyPostRepository.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
  src/main/java/com/web/stard/global/utils/SchedulerUtils.java
Labels: :sparkles: feature, :recycle: refactor

#68 스터디 목록 조회 시, 스크랩 여부 필드 추가
  build.gradle
  src/main/java/com/web/stard/domain/starScrap/repository/StarScrapRepository.java
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#69 feat: 스터디 팀블로그 - 장소 추천 기능 구현
  src/main/java/com/web/stard/domain/member/domain/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/post/domain/dto/response/PostResponseDto.java
  src/main/java/com/web/stard/domain/teamBlog/api/LocationController.java
  src/main/java/com/web/stard/domain/teamBlog/domain/dto/response/Location.java
  src/main/java/com/web/stard/domain/teamBlog/domain/dto/response/ScheduleResponseDto.java
  src/main/java/com/web/stard/domain/teamBlog/domain/dto/response/ToDoResponseDto.java
  src/main/java/com/web/stard/domain/teamBlog/service/LocationService.java
  src/main/java/com/web/stard/domain/teamBlog/service/impl/LocationServiceImpl.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
Labels: :sparkles: feature

#70 feat: WebConfig에 프론트 배포 주소 추가
  src/main/java/com/web/stard/domain/chat/domain/entity/ChatMessage.java
  src/main/java/com/web/stard/domain/chat/domain/entity/ChatRoom.java
  src/main/java/com/web/stard/domain/chat/domain/enums/MessageType.java
  src/main/java/com/web/stard/global/config/WebConfig.java
Labels: :sparkles: feature

#71 chore: cors 설정 추가
  src/main/java/com/web/stard/global/config/WebConfig.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
Labels: :recycle: refactor

#72 chore: origin 설정 추가
  src/main/java/com/web/stard/global/config/WebConfig.java
Labels: :recycle: refactor

#73 refactor: responseDto에 createdAt 필드 추가, JVM 타임존 설정
  src/main/java/com/web/stard/StardApplication.java
  src/main/java/com/web/stard/domain/post/domain/dto/response/PostResponseDto.java
  src/main/java/com/web/stard/domain/reply/domain/dto/response/ReplyResponseDto.java
Labels: :recycle: refactor

#75 JWT 토큰 재발급 API 구현 / 로그인, 로그아웃 시 Refresh Token 쿠키 추가 및 삭제 기능 구현
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/service/AuthService.java
  src/main/java/com/web/stard/domain/member/service/impl/AuthServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/global/config/security/JwtTokenProvider.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
  src/main/java/com/web/stard/global/utils/CookieUtils.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#77 feat: 비밀번호 찾기 및 재설정 API 구현
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/domain/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/member/service/AuthService.java
  src/main/java/com/web/stard/domain/member/service/MemberService.java
  src/main/java/com/web/stard/domain/member/service/impl/AuthServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
  src/main/java/com/web/stard/global/utils/EmailUtils.java
Labels: :sparkles: feature, :recycle: refactor

#76 feat: 회원 탈퇴
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/domain/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/member/service/AuthService.java
  src/main/java/com/web/stard/domain/member/service/MemberService.java
  src/main/java/com/web/stard/domain/member/service/impl/AuthServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/UnknownMemberService.java
  src/main/java/com/web/stard/domain/reply/repository/ReplyRepository.java
  src/main/java/com/web/stard/domain/report/repository/ReportRepository.java
  src/main/java/com/web/stard/domain/report/service/ReportService.java
  src/main/java/com/web/stard/domain/report/service/impl/ReportServiceImpl.java
  src/main/java/com/web/stard/domain/starScrap/repository/StarScrapRepository.java
  src/main/java/com/web/stard/domain/study/domain/entity/StudyApplicant.java
  src/main/java/com/web/stard/domain/study/domain/entity/StudyMember.java
  src/main/java/com/web/stard/domain/study/repository/StudyApplicantRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/web/stard/domain/teamBlog/domain/entity/Assignee.java
  src/main/java/com/web/stard/domain/teamBlog/domain/entity/Evaluation.java
  src/main/java/com/web/stard/domain/teamBlog/repository/AssigneeRepository.java
  src/main/java/com/web/stard/domain/teamBlog/repository/EvaluationRepository.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
  src/main/java/com/web/stard/global/utils/SchedulerUtils.java
Labels: :sparkles: feature, :recycle: refactor

#78 feat: 스터디 DetailInfo isScrapped 필드 추가
  src/main/java/com/web/stard/domain/starScrap/service/impl/StarScrapServiceImpl.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
Labels: :sparkles: feature

#79 feat: 채팅 기능 구현
  build.gradle
  src/main/java/com/web/stard/domain/chat/api/ChatRoomController.java
  src/main/java/com/web/stard/domain/chat/api/GreetingController.java
  src/main/java/com/web/stard/domain/chat/domain/dto/response/ChatResponseDto.java
  src/main/java/com/web/stard/domain/chat/domain/entity/ChatMessage.java
  src/main/java/com/web/stard/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/web/stard/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/web/stard/domain/chat/service/ChatMessageService.java
  src/main/java/com/web/stard/domain/chat/service/ChatRoomService.java
  src/main/java/com/web/stard/domain/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/web/stard/domain/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/web/stard/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
Labels: :sparkles: feature

#81 feat: 권한 조회 API 구현
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/service/AuthService.java
  src/main/java/com/web/stard/domain/member/service/impl/AuthServiceImpl.java
Labels: :sparkles: feature

#82 [FEAT] 스터디 모집 게시글 조회수 증가 로직 / 주간 인기 태그 Top 5 목록 조회
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/domain/entity/StudyTag.java
  src/main/java/com/web/stard/domain/study/domain/entity/Tag.java
  src/main/java/com/web/stard/domain/study/repository/StudyRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyTagRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
Labels: :recycle: refactor

#84 feat: 마이페이지 남은 기능 구현
  src/main/java/com/web/stard/domain/chat/domain/entity/ChatMessage.java
  src/main/java/com/web/stard/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/reply/domain/dto/response/ReplyResponseDto.java
  src/main/java/com/web/stard/domain/reply/repository/ReplyRepository.java
  src/main/java/com/web/stard/domain/reply/service/ReplyService.java
  src/main/java/com/web/stard/domain/reply/service/impl/ReplyServiceImpl.java
  src/main/java/com/web/stard/domain/starScrap/service/impl/StarScrapServiceImpl.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/repository/StudyApplicantRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
  src/main/java/com/web/stard/domain/teamBlog/service/impl/EvaluationServiceImpl.java
  src/main/java/com/web/stard/domain/teamBlog/service/impl/ScheduleServiceImpl.java
  src/main/java/com/web/stard/domain/teamBlog/service/impl/StudyPostServiceImpl.java
Labels: :sparkles: feature

#86 실시간 알림 기능 구현
  build.gradle
  src/main/java/com/web/stard/domain/notification/api/NotificationController.java
  src/main/java/com/web/stard/domain/notification/domain/dto/request/NotificationRequest.java
  src/main/java/com/web/stard/domain/notification/domain/dto/response/NotificationResponse.java
  src/main/java/com/web/stard/domain/notification/domain/entity/Notification.java
  src/main/java/com/web/stard/domain/notification/domain/enums/NotificationType.java
  src/main/java/com/web/stard/domain/notification/repository/EmitterRepository.java
  src/main/java/com/web/stard/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/web/stard/domain/notification/repository/NotificationRepository.java
  src/main/java/com/web/stard/domain/notification/service/NotificationService.java
  src/main/java/com/web/stard/domain/notification/service/impl/NotificationServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#87 feat: 알림 목록 조회, 읽음 처리 로직 구현
  src/main/java/com/web/stard/domain/notification/api/NotificationController.java
  src/main/java/com/web/stard/domain/notification/domain/dto/response/NotificationResponse.java
  src/main/java/com/web/stard/domain/notification/repository/NotificationRepository.java
  src/main/java/com/web/stard/domain/notification/service/NotificationService.java
  src/main/java/com/web/stard/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/web/stard/domain/reply/service/impl/ReplyServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#88 feat: 팀블로그 스터디원 조회 API 구현
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#90 feat: 남은 기능 구현
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/domain/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/domain/member/domain/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/member/domain/entity/Profile.java
  src/main/java/com/web/stard/domain/member/service/AuthService.java
  src/main/java/com/web/stard/domain/member/service/MemberService.java
  src/main/java/com/web/stard/domain/member/service/impl/AuthServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
Labels: :sparkles: feature, :recycle: refactor
