Repository Hanium2023-WeB/starD-backend-refactoring, pull requests merged in 2024-10, with the labels that each got.

#6 feat: 회원가입 api 기본 구현
  build.gradle
  src/main/java/com/web/stard/StardApplication.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/application/MemberService.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/domain/Address.java
  src/main/java/com/web/stard/domain/member/domain/Interest.java
  src/main/java/com/web/stard/domain/member/domain/Member.java
  src/main/java/com/web/stard/domain/member/domain/Profile.java
  src/main/java/com/web/stard/domain/member/domain/enums/InterestField.java
  src/main/java/com/web/stard/domain/member/domain/enums/Role.java
  src/main/java/com/web/stard/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/member/repository/MemberRepository.java
  src/main/java/com/web/stard/domain/test/api/TestController.java
  src/main/java/com/web/stard/global/config/WebConfig.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
  src/main/java/com/web/stard/global/config/swagger/SwaggerConfig.java
  src/main/java/com/web/stard/global/domain/BaseEntity.java
  src/main/java/com/web/stard/global/dto/CommonResponse.java
  src/main/java/com/web/stard/global/dto/Response.java
  src/main/java/com/web/stard/global/dto/TokenInfo.java
  src/main/java/com/web/stard/global/error/CustomException.java
  src/main/java/com/web/stard/global/error/CustomExceptionHandler.java
  src/main/java/com/web/stard/global/error/ErrorCode.java
  src/main/java/com/web/stard/global/error/ErrorResponseEntity.java
Labels: :memo: docs, :sparkles: feature

#8 feat: 개인정보 수정 - 정보 반환, 닉네임, 전화번호, 거주지
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/application/MemberService.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/domain/Address.java
  src/main/java/com/web/stard/domain/member/domain/Member.java
  src/main/java/com/web/stard/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/member/repository/InterestRepository.java
Labels: :sparkles: feature

#9 feat: 회원가입 추가 정보 저장 및 프로필 구현
  build.gradle
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/application/MemberService.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/domain/Interest.java
  src/main/java/com/web/stard/domain/member/domain/Member.java
  src/main/java/com/web/stard/domain/member/domain/Profile.java
  src/main/java/com/web/stard/domain/member/domain/enums/InterestField.java
  src/main/java/com/web/stard/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/member/repository/MemberRepository.java
  src/main/java/com/web/stard/global/config/aws/S3Config.java
  src/main/java/com/web/stard/global/config/aws/S3Manager.java
  src/main/java/com/web/stard/global/config/swagger/SwaggerConfig.java
  src/main/java/com/web/stard/global/error/ErrorCode.java
Labels: :memo: docs, :sparkles: feature

#10 merge: dev 브랜치 코드를 main 브랜치에 병합
  build.gradle
  src/main/java/com/web/stard/StardApplication.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/application/MemberService.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/domain/Interest.java
  src/main/java/com/web/stard/domain/member/domain/Member.java
  src/main/java/com/web/stard/domain/member/domain/Profile.java
  src/main/java/com/web/stard/domain/member/domain/enums/InterestField.java
  src/main/java/com/web/stard/domain/member/domain/enums/Role.java
  src/main/java/com/web/stard/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/member/repository/InterestRepository.java
  src/main/java/com/web/stard/domain/member/repository/MemberRepository.java
  src/main/java/com/web/stard/domain/test/api/TestController.java
  src/main/java/com/web/stard/global/config/WebConfig.java
  src/main/java/com/web/stard/global/config/aws/S3Config.java
  src/main/java/com/web/stard/global/config/aws/S3Manager.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
  src/main/java/com/web/stard/global/config/swagger/SwaggerConfig.java
  src/main/java/com/web/stard/global/domain/BaseEntity.java
  src/main/java/com/web/stard/global/dto/CommonResponse.java
  src/main/java/com/web/stard/global/dto/Response.java
  src/main/java/com/web/stard/global/dto/TokenInfo.java
  src/main/java/com/web/stard/global/error/CustomException.java
  src/main/java/com/web/stard/global/error/CustomExceptionHandler.java
  src/main/java/com/web/stard/global/error/ErrorCode.java
  src/main/java/com/web/stard/global/error/ErrorResponseEntity.java
Labels: :sparkles: feature

#12 feat: 공지사항 기능 구현
  src/main/java/com/web/stard/domain/admin/api/NoticeController.java
  src/main/java/com/web/stard/domain/admin/application/NoticeService.java
  src/main/java/com/web/stard/domain/admin/application/impl/NoticeServiceImpl.java
  src/main/java/com/web/stard/domain/admin/dto/request/NoticeRequestDto.java
  src/main/java/com/web/stard/domain/admin/dto/response/NoticeResponseDto.java
  src/main/java/com/web/stard/domain/board/global/domain/Post.java
  src/main/java/com/web/stard/domain/board/global/domain/enums/Category.java
  src/main/java/com/web/stard/domain/board/global/domain/enums/PostType.java
  src/main/java/com/web/stard/domain/board/global/repository/PostRepository.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/global/error/ErrorCode.java
Labels: :sparkles: feature

#13 feat: 로그인 기능 구현
  build.gradle
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/application/MemberService.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/application/impl/UserDetailsServiceImpl.java
  src/main/java/com/web/stard/domain/member/domain/Member.java
  src/main/java/com/web/stard/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/domain/member/repository/MemberRepository.java
  src/main/java/com/web/stard/global/config/aws/S3Manager.java
  src/main/java/com/web/stard/global/config/redis/RedisConfig.java
  src/main/java/com/web/stard/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/web/stard/global/config/security/JwtExceptionFilter.java
  src/main/java/com/web/stard/global/config/security/JwtTokenProvider.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
  src/main/java/com/web/stard/global/dto/TokenInfo.java
  src/main/java/com/web/stard/global/exception/CustomException.java
  src/main/java/com/web/stard/global/exception/CustomExceptionHandler.java
  src/main/java/com/web/stard/global/exception/ErrorResponseEntity.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
  src/main/java/com/web/stard/global/utils/RedisUtils.java
Labels: :sparkles: feature, :recycle: refactor

#17 #14 이메일 인증 기능 구현
  build.gradle
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/application/MemberService.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/global/config/email/EmailConfig.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
  src/main/java/com/web/stard/global/utils/EmailUtils.java
Labels: :sparkles: feature

#18 feat: 개인정보 수정
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/application/MemberService.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/member/domain/Interest.java
  src/main/java/com/web/stard/domain/member/domain/Member.java
  src/main/java/com/web/stard/domain/member/domain/enums/InterestField.java
  src/main/java/com/web/stard/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/domain/member/dto/response/MemberResponseDto.java
Labels: :sparkles: feature

#20 feat: 커뮤니티 기능 구현
  src/main/java/com/web/stard/domain/board/community/api/CommunityController.java
  src/main/java/com/web/stard/domain/board/community/application/CommunityService.java
  src/main/java/com/web/stard/domain/board/community/application/impl/CommunityServiceImpl.java
  src/main/java/com/web/stard/domain/board/community/dto/request/CommRequestDto.java
  src/main/java/com/web/stard/domain/board/community/dto/response/CommResponseDto.java
  src/main/java/com/web/stard/domain/board/global/domain/Post.java
  src/main/java/com/web/stard/domain/board/global/domain/enums/Category.java
  src/main/java/com/web/stard/domain/board/global/repository/PostRepository.java
Labels: :sparkles: feature

#23 refactor: member, auth 구분 및 예외 응답 통일
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/application/AuthService.java
  src/main/java/com/web/stard/domain/member/application/MemberService.java
  src/main/java/com/web/stard/domain/member/application/impl/AuthServiceImpl.java
  src/main/java/com/web/stard/domain/member/application/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/global/exception/CustomExceptionHandler.java
  src/main/java/com/web/stard/global/exception/ErrorResponseEntity.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
Labels: :recycle: refactor
