Repository Hanium2023-WeB/starD-backend-refactoring, pull requests merged in 2025-01, with the labels that each got.

#93 fix: 게시글 등록 DTO에 기본 생성자 추가
  src/main/java/com/web/stard/domain/post/domain/dto/request/PostRequestDto.java
Labels: :bug: bug

#94 fix: 커뮤니티 검색 쿼리 수정 / feat: 스터디 지원 동기 조회 API 구현
  src/main/java/com/web/stard/domain/post/repository/PostRepository.java
  src/main/java/com/web/stard/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/repository/StudyApplicantRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#96 fix: 알림 및 스터디 모집 게시글, 댓글 DTO 수정
  src/main/java/com/web/stard/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/web/stard/domain/reply/domain/dto/response/ReplyResponseDto.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
Labels: :bug: bug, :sparkles: feature

#99 feat: 스웨거 에러 응답값 커스텀 어노테이션 구현
  src/main/java/com/web/stard/domain/teamBlog/api/EvaluationController.java
  src/main/java/com/web/stard/global/config/swagger/SwaggerConfig.java
  src/main/java/com/web/stard/global/dto/ErrorResponseDto.java
  src/main/java/com/web/stard/global/exception/ApiErrorCodeExample.java
  src/main/java/com/web/stard/global/exception/ApiErrorCodeExamples.java
  src/main/java/com/web/stard/global/exception/ExampleHolder.java
Labels: :sparkles: feature

#100 feat: 스웨거 에러 응답 값 Example Description추가
  src/main/java/com/web/stard/global/config/swagger/SwaggerConfig.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
  src/main/java/com/web/stard/global/exception/error/ExplainError.java
Labels: :sparkles: feature

#101 feat: 스웨거 에러 응답 값 추가
  src/main/java/com/web/stard/domain/admin/api/FaqController.java
  src/main/java/com/web/stard/domain/admin/api/NoticeController.java
  src/main/java/com/web/stard/domain/chat/api/ChatRoomController.java
  src/main/java/com/web/stard/domain/member/api/AuthController.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/post/api/CommunityController.java
  src/main/java/com/web/stard/domain/post/api/QnaController.java
  src/main/java/com/web/stard/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/web/stard/domain/reply/api/ReplyController.java
  src/main/java/com/web/stard/domain/report/api/ReportController.java
  src/main/java/com/web/stard/domain/starScrap/api/StarScrapController.java
  src/main/java/com/web/stard/domain/starScrap/service/impl/StarScrapServiceImpl.java
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
  src/main/java/com/web/stard/domain/teamBlog/api/EvaluationController.java
  src/main/java/com/web/stard/domain/teamBlog/api/LocationController.java
  src/main/java/com/web/stard/domain/teamBlog/api/ScheduleController.java
  src/main/java/com/web/stard/domain/teamBlog/api/StudyPostController.java
  src/main/java/com/web/stard/domain/teamBlog/api/ToDoController.java
  src/main/java/com/web/stard/domain/teamBlog/service/impl/ToDoServiceImpl.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
Labels: :sparkles: feature, :recycle: refactor

#103 fix: 에러 수정
  src/main/java/com/web/stard/domain/post/domain/dto/response/PostResponseDto.java
  src/main/java/com/web/stard/domain/report/domain/dto/response/ReportResponseDto.java
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
  src/main/java/com/web/stard/domain/teamBlog/domain/dto/request/EvaluationRequestDto.java
  src/main/java/com/web/stard/domain/teamBlog/domain/dto/request/ScheduleRequestDto.java
  src/main/java/com/web/stard/domain/teamBlog/domain/dto/request/ToDoRequestDto.java
  src/main/java/com/web/stard/global/utils/CookieUtils.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#104 fix: 로컬 환경에서 파일 업로드, 삭제, 다운로드 로직 구현 / 스터디 관련 코드 수정
  src/main/java/com/web/stard/domain/member/service/impl/AuthServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/report/service/impl/ReportServiceImpl.java
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/web/stard/domain/study/repository/StudyRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
  src/main/java/com/web/stard/domain/teamBlog/service/impl/StudyPostServiceImpl.java
  src/main/java/com/web/stard/global/exception/error/ErrorCode.java
  src/main/java/com/web/stard/global/utils/FileUtils.java
  src/main/java/com/web/stard/global/utils/SchedulerUtils.java
Labels: :bug: bug, :recycle: refactor

#106 fix: todo 관련 에러 수정
  src/main/java/com/web/stard/domain/teamBlog/domain/dto/response/ToDoResponseDto.java
  src/main/java/com/web/stard/domain/teamBlog/service/impl/ToDoServiceImpl.java
Labels: :bug: bug

#108 fix: 내가 작성한 댓글 조회 시 게시글 타입이 STUDYPOST인 경우, study 아이디 넘겨주기
  src/main/java/com/web/stard/domain/reply/domain/dto/response/ReplyResponseDto.java
  src/main/java/com/web/stard/domain/reply/service/impl/ReplyServiceImpl.java
  src/main/java/com/web/stard/global/dto/Response.java
Labels: :bug: bug

#110 fix: 로컬에서 프로필 이미지 조회 / 투두 DTO에 담당자 고유 id 필드 추가
  src/main/java/com/web/stard/domain/file/api/FileController.java
  src/main/java/com/web/stard/domain/member/api/MemberController.java
  src/main/java/com/web/stard/domain/member/domain/dto/request/MemberRequestDto.java
  src/main/java/com/web/stard/domain/member/domain/dto/response/MemberResponseDto.java
  src/main/java/com/web/stard/domain/member/domain/entity/Profile.java
  src/main/java/com/web/stard/domain/member/service/MemberService.java
  src/main/java/com/web/stard/domain/member/service/impl/AuthServiceImpl.java
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/post/domain/dto/response/PostResponseDto.java
  src/main/java/com/web/stard/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/web/stard/domain/reply/domain/dto/response/ReplyResponseDto.java
  src/main/java/com/web/stard/domain/reply/service/impl/ReplyServiceImpl.java
  src/main/java/com/web/stard/domain/starScrap/service/impl/StarScrapServiceImpl.java
  src/main/java/com/web/stard/domain/study/api/StudyController.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/web/stard/domain/study/service/StudyService.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
  src/main/java/com/web/stard/domain/teamBlog/domain/dto/response/ToDoResponseDto.java
  src/main/java/com/web/stard/global/config/security/SecurityConfig.java
  src/main/java/com/web/stard/global/utils/FileUtils.java
Labels: :bug: bug

#112 fix: 이미지 조회 관련 코드 수정
  src/main/java/com/web/stard/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/web/stard/domain/post/domain/dto/response/PostResponseDto.java
  src/main/java/com/web/stard/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/web/stard/domain/reply/domain/dto/response/ReplyResponseDto.java
  src/main/java/com/web/stard/domain/reply/service/impl/ReplyServiceImpl.java
  src/main/java/com/web/stard/domain/starScrap/repository/StarScrapRepository.java
  src/main/java/com/web/stard/domain/starScrap/service/impl/StarScrapServiceImpl.java
  src/main/java/com/web/stard/domain/study/domain/dto/response/StudyResponseDto.java
  src/main/java/com/web/stard/domain/study/service/impl/StudyServiceImpl.java
Labels: :bug: bug
